# This is a basic workflow to help you get started with Actions

name:  Greetings

# Controls when the workflow will run
on: issues

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: bartick/custom-interactions@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          Thank you for opening this issue in our repository, <br>I have just notified to Mr Vinayak aka @malivinayak, he will get in touch with you soon regarding this issue.
        issue-once: false
        issue-number: 10
